---
- name: Add hotjar job
  template: 
        src=hotjar.conf.j2
        dest=/etc/init/hotjar.conf
        owner=root
        group=root
        mode=0644
- name: Add hotjar-instance job
  template: 
        src="hotjar-instance.conf.j2"
        dest="/etc/init/hotjar-instance.conf"
        owner=root
        group=root
        mode=0644
- name: Create the application directories
  file: path={{ item }}
        owner=deploy
        group=deploy
        state=directory
  with_items:
    - "{{ hotjar_home }}"
    - "{{ hotjar_home }}/bin"
    - "{{ hotjar_home }}/apps"
    - /var/log/hotjar
- name: Copy hotjar scripts
  copy: src="{{ item }}"
        dest="{{ hotjar_home }}/bin"
        owner=deploy
        group=deploy
        mode=0755
  with_items:
    - hotjar
    - start-app